address = "[::]:8000"

[auth]
algorithm = "ES256"
keyfile = "public_key.pem"
issuer = "demogorgon"

[backends.cats]
url = "https://http.cat"
scope = "cats:cat"

[backends.hass]
url = "https://homeassistant.example.com/api"
cert_auth = { PEMFile = "clientcert.pem" }
headers = {"authorization" = "Bearer foobar"}
scope = "hass:*"